"""Reading/writing ASS scripts: assemble the signs file, merge it into the dialogue file."""
import os, re, shutil
from .text import parse_style

MARK = "; generated by anime-typeset"
STYLE_FORMAT = ("Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, "
                "Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, "
                "MarginL, MarginR, MarginV, Encoding")
EVENT_FORMAT = "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text"


def read_lines(path):
    with open(path, encoding="utf-8-sig") as fh:
        return fh.read().splitlines()


def write_lines(path, lines):
    with open(path, "w", encoding="utf-8-sig", newline="\r\n") as fh:
        fh.write("\n".join(lines) + "\n")


def section(lines, name):
    i = lines.index(name)
    j = next((k for k in range(i + 1, len(lines)) if lines[k].startswith("[")), len(lines))
    return i, j


def t2cs(t):
    h, m, s = t.split(":")
    return int(h) * 360000 + int(m) * 6000 + round(float(s) * 100)


def ev_fields(line):
    kind, rest = line.split(":", 1)
    p = rest.strip().split(",", 9)
    return kind, p


def ev_style(line):
    return ev_fields(line)[1][3]


def ev_text(line):
    return ev_fields(line)[1][9]


BACKUP_DIR = "исходники"


def backup_path(path, suffix=""):
    """where a kept copy of `path` goes: the 'исходники' folder next to it (the release folder stays clean)"""
    d, name = os.path.split(path)
    root, ext = os.path.splitext(name)
    return os.path.join(d, BACKUP_DIR, f"{root}{suffix}{ext}")


def backup_once(path, suffix=""):
    """keep the user's original file the first time we overwrite it (in исходники/, same name)"""
    if not os.path.exists(path):
        return None
    if MARK in "\n".join(read_lines(path)[:20]):
        return None
    root, ext = os.path.splitext(path)
    b = backup_path(path, suffix)
    if not os.path.exists(b) and not os.path.exists(f"{root} (исходник){ext}"):   # (the old layout)
        os.makedirs(os.path.dirname(b), exist_ok=True)
        shutil.copy2(path, b)
        return b
    return None


def is_drawing(line):
    return "\\p1" in ev_text(line)


def header(title, playres, ycbcr, styles):
    return ["[Script Info]", f"Title: {title}", MARK, "ScriptType: v4.00+", "WrapStyle: 2", "ScaledBorderAndShadow: yes",
            f"YCbCr Matrix: {ycbcr}", f"PlayResX: {playres[0]}", f"PlayResY: {playres[1]}",
            f"LayoutResX: {playres[0]}", f"LayoutResY: {playres[1]}", "",
            "[V4+ Styles]", STYLE_FORMAT] + styles + ["", "[Events]", EVENT_FORMAT]


TS = "ts"   # Effect field of every generated event: lets merge find (and replace) a previous merge safely


def fix_actor(line):
    kind, p = ev_fields(line)
    p[4] = "маска" if is_drawing(line) else "Надпись"
    p[8] = TS
    return f"{kind}: " + ",".join(p)


def assemble(ctx, out_path, title=None):
    """write the signs script from the built items (lines/<id>.json), one commented block per item"""
    events, used = [], set()
    missing = []
    for it in ctx.items():
        data = ctx.load_lines(it["id"])
        if data is None:
            missing.append(it["id"]); continue
        lines = data["lines"]
        if not lines:
            continue
        st = min((ev_fields(l)[1][1] for l in lines), key=t2cs)
        events.append(f"Comment: 0,{st},{st},{ev_style(lines[0])},,0,0,0,{TS},=== {it.get('name', it['id'])} ===")
        texts = [fix_actor(l) for l in lines if not is_drawing(l)]
        masks = [fix_actor(l) for l in lines if is_drawing(l)]
        events += texts + masks
        used |= {ev_style(l) for l in lines}
    if missing:
        print(f"  not built yet (skipped): {', '.join(missing)}")
    styles = [l for l in ctx.all_style_lines if parse_style(l)["Name"] in used]
    backup_once(out_path)
    name = title or os.path.splitext(os.path.basename(out_path))[0]
    write_lines(out_path, header(name, ctx.playres, ctx.video.ycbcr, styles) + events)
    return len(events)


def event_key(line):
    _, p = ev_fields(line)
    return (t2cs(p[1]), t2cs(p[2]), p[3], p[9])


def source_event_keys(src):
    """(start, end, style, text) of every event of the translator's signs file (path or list of lines)"""
    if isinstance(src, (list, tuple)):
        return {event_key(l) for l in src if l.startswith("Dialogue:")}
    lines = read_lines(src)
    e0, e1 = section(lines, "[Events]")
    return {event_key(l) for l in lines[e0 + 2:e1] if l.startswith("Dialogue:")}


def merge(signs_path, subs_path, ycbcr, source_signs=None, drop_styles=()):
    """Replace the old sign lines of the dialogue script with the new signs.
    Removed from the dialogue script: events identical to an event of the translator's signs file
    (start, end, style, text - CR puts signs into the full subs with the *dialogue* styles, so removing by
    style would delete dialogue), events of a previous merge (Effect 'ts'), and events of drop_styles.
    Style definitions are removed only when nothing uses them any more. Sign layers go below the dialogue."""
    backup = backup_once(subs_path)
    src = read_lines(subs_path)
    sig = read_lines(signs_path)
    si0, si1 = section(src, "[Script Info]")
    info = [l for l in src[si0:si1] if not l.startswith("YCbCr Matrix") and l != MARK]
    k = next((i for i, l in enumerate(info) if l.startswith("ScaledBorderAndShadow")), len(info) - 1)
    info.insert(k + 1, f"YCbCr Matrix: {ycbcr}")
    while info and info[-1] == "":
        info.pop()
    st0, st1 = section(src, "[V4+ Styles]")
    old = [l for l in src[st0 + 1:st1] if l.strip()]
    fmt = old[0] if old and old[0].startswith("Format:") else STYLE_FORMAT
    old_styles = [l for l in old if l.startswith("Style:")]
    ev0, ev1 = section(src, "[Events]")
    ev_fmt = src[ev0 + 1]
    events = [l for l in src[ev0 + 2:ev1] if l.strip()]
    src_keys = (source_event_keys(source_signs) if isinstance(source_signs, (list, tuple))
                else source_event_keys(source_signs) if source_signs and os.path.exists(source_signs) else set())
    drop_styles = set(drop_styles or ())

    def is_old_sign(l):
        if not l.startswith(("Dialogue:", "Comment:")):
            return False
        _, p = ev_fields(l)
        return p[8] == TS or p[3] in drop_styles or (l.startswith("Dialogue:") and event_key(l) in src_keys)

    removed = [l for l in events if is_old_sign(l)]
    dlg_before = [_no_layer(l) for l in events if l.startswith("Dialogue:") and not is_old_sign(l)]
    events = [l for l in events if not is_old_sign(l)]
    still_used = {ev_style(l) for l in events if l.startswith(("Dialogue:", "Comment:"))}
    gone = {ev_style(l) for l in removed} - still_used       # styles only the old signs used
    keep = [l for l in old_styles if parse_style(l)["Name"] not in gone]
    have = {parse_style(l)["Name"] for l in keep}
    s0, s1 = section(sig, "[V4+ Styles]")
    new = [l for l in sig[s0 + 1:s1] if l.startswith("Style:") and parse_style(l)["Name"] not in have]
    e0, e1 = section(sig, "[Events]")
    blocks, cur = [], None
    for l in sig[e0 + 2:e1]:
        if not l.strip():
            continue
        if l.startswith("Comment:") and "===" in l or cur is None:
            cur = [l]; blocks.append(cur)
        else:
            cur.append(l)
    sign_layers = sorted({int(ev_fields(l)[1][0]) for b in blocks for l in b if l.startswith("Dialogue:")})
    dlg_layers = [int(ev_fields(l)[1][0]) for l in events if l.startswith("Dialogue:")]
    n = len(sign_layers)
    lmap = {L: i + 1 for i, L in enumerate(sign_layers)}
    bump = 0
    if dlg_layers and min(dlg_layers) <= n:
        bump = n + 1 - min(dlg_layers)
        events = [_relayer(l, int(ev_fields(l)[1][0]) + bump) if l.startswith(("Dialogue:", "Comment:")) else l for l in events]

    def start(l):
        return t2cs(ev_fields(l)[1][1])
    for b in blocks:
        b[:] = [_relayer(l, lmap[int(ev_fields(l)[1][0])]) if l.startswith("Dialogue:") else l for l in b]
        b[:] = [_mark(l) for l in b]
        bs = min(start(l) for l in b if l.startswith("Dialogue:")) if any(l.startswith("Dialogue:") for l in b) else start(b[0])
        pos = next((i for i, l in enumerate(events) if l.startswith(("Dialogue:", "Comment:")) and start(l) >= bs), len(events))
        events[pos:pos] = b
    out = info + ["", "[V4+ Styles]", fmt] + keep + new + ["", "[Events]", ev_fmt] + events + src[ev1:]
    write_lines(subs_path, out)
    dlg_after = [_no_layer(l) for l in read_lines(subs_path) if l.startswith("Dialogue:") and ev_fields(l)[1][8] != TS]
    # the dialogue must come out the same line for line (text, times, style, actor, order); only Layer may move up
    return dict(dialogue_before=len(dlg_before), dialogue_after=len(dlg_after), dialogue_same=dlg_before == dlg_after,
                dialogue_diff=next((i for i, (x, y) in enumerate(zip(dlg_before, dlg_after)) if x != y), None),
                removed=len(removed), inserted=sum(len(b) for b in blocks), blocks=len(blocks),
                backup=backup, dialogue_bump=bump,
                styles_removed=sorted(gone - {parse_style(l)["Name"] for l in new}))   # not re-added by the signs


def _no_layer(line):
    kind, p = ev_fields(line)
    return f"{kind}: " + ",".join(p[1:])


def _mark(line):
    kind, p = ev_fields(line)
    p[8] = TS
    return f"{kind}: " + ",".join(p)


def _relayer(line, layer):
    kind, p = ev_fields(line)
    p[0] = str(layer)
    return f"{kind}: " + ",".join(p)
